[general]
protocol = "memcache"
interval = 60 # seconds
windows = 5 # run for 5 intervals
clients = 1 # use a single client thread
poolsize = 1 # each client has 1 connection per endpoint
tcp_nodelay = false # do not enable tcp_nodelay
request_timeout = 200 # milliseconds
connect_timeout = 200 # milliseconds
tls_key = "key.pem" # client key
tls_cert = "client.crt" # client certificate
tls_ca = "ca.pem" # certificate authority to validate server certificate

[[keyspace]]
length = 8 # 8 byte keys
count = 10_000_000 # limit to 10M keys
weight = 1 # this keyspace has a weight of 1
commands = [ # get:set ratio is 1:1
    {weight = 1, action= {type = "get"}},
    {weight = 1, action= {type = "set"}},
]
values = [ # value length will always be 64 bytes
    {length = 64, weight = 1},
]
