[package]
name = "datastructures"
version = "0.2.1"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"

[dependencies]
logger = { path = "../logger" }
parking_lot = "0.7.1"
time = "0.1.42"
